name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

env:
  PY_ALL: 3.7 3.8 3.9 3.10 3.11 pypy3.9

jobs:
  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.7", "3.8", "3.9", "3.10", "3.11", "pypy3.7", "pypy3.8", "pypy3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install
        run: pip install '.[dev]'
      - name: Run tests
        run: pytest --verbose

  python-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: pip install '.[dev]'
      - name: black
        run: black --check tests/ seahash.pyi

  arm:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: pyo3/maturin-action@v1
        with:
          command: build
          args: --release --interpreter ${{ env.PY_ALL }}
          target: aarch64
          manylinux: auto

  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: $HOME/.cargo
          key: cargo-${{ hashFiles('Cargo.lock') }}
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: Check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
